//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEmpresa.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class productes
    {
        public int id_produte { get; set; }
        public string producte { get; set; }
        public decimal preu { get; set; }
    }
}
